---
- name: Upgrade all packages
  ansible.builtin.apt:
    name: "*"
    update_cache: true
    cache_valid_time: 3600

- name: Install nginx
  ansible.builtin.apt:
    name: nginx
    state: present
